### ISSUE TITLE
feat: allow filtering individual fields in response

### ISSUE THREAD

**Issue by Foorack** [Mermade/openapi-filter#105]
Feature request to allow filtering individual fields in a response. The use case for this would be cases where the API either secretly or temporarily returns a specific field, which you need to specify in the spec due to API generation but doesn't want to document on the public docs.

I could possibly try make a PR, but wanted to post it as Issue to hear thoughts first.

**Comment by MikeRalphson** [comment]
Using the original mechanism for this tool (tagging an object with a flag extension such as `x-internal`), this is already possible. See https://github.com/Mermade/openapi-filter/blob/a08c6ac6897eb55e23ca7fb4c17bab092e6cbd50/test/issue105a/input.yaml#L5-L20

When you say "due to API generation", do you mean your OpenAPI definition is generated from code, and you can't introduce extension properties?

If so, how do you see specifying the property or properties to filter out? By having JSON-reference paths on the command-line, or some other method?

**Comment by Foorack** [comment]
Okay, you're right. It seems like this feature is already implemented.
![image](https://user-images.githubusercontent.com/5008081/127296604-956f7972-f0da-41b5-b372-ac1db1633cdd.png)

Thank you, closing this ticket. :+1: 

(And with "API generation", I meant that we generate SDK's from the OpenAPI specification.)
