### ISSUE TITLE
Accidental 3.0 release?

### ISSUE THREAD

**Issue by bzmw** [Mermade/openapi-filter#43]
Hey there,
Dependabot opened a 3.0.0 update for me this morning, was this an accidental publish? I don't see a tag or changelog as has been what is historically done in this project.

**Comment by MikeRalphson** [comment]
Thanks for reminding me to push the `package.json` change and the tag! 

We were conservative and bumped the version because the output of using `--inverse` and `--valid` together has been changed to include all nested `$ref`s, even though the contract of the program's API has not changed. See #39 for details.

I will add a CHANGELOG entry. Thanks again.

**Comment by MikeRalphson** [comment]
`CHANGELOG.md` added. Thanks again for flagging this up.
